apiVersion: v1
kind: Service
metadata:
  name: ves-collector
  namespace: nonrtric
  labels:
    run: ves-collector
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    nodePort: 31760
  - port: 8443
    name: https
    nodePort: 31761
  selector:
    run: ves-collector
