#  ============LICENSE_START===============================================
#  Copyright (C) 2023 Nordix Foundation. All rights reserved.
#  ========================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ============LICENSE_END=================================================
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dfc
  namespace: nonrtric
  labels:
    run: dfc
spec:
  replicas: 1
  serviceName: dfc
  selector:
    matchLabels:
      run: dfc
  template:
    metadata:
      labels:
        run: dfc
    spec:
      volumes:
        - name: config-truststore
          configMap:
            name: dfc-cm-truststore
        - name: config-cm
          configMap:
            name: dfc-cm
      containers:
      - name: dfc
        securityContext:
          runAsUser: 0     # Need to run as root - needed when writing to hostpath
        #image: onap/org.onap.dcaegen2.collectors.datafile.datafile-app-server:2.5.14
        image: nexus3.o-ran-sc.org:10004/o-ran-sc/nonrtric-plt-ranpm-datafilecollector:1.0.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8100
        volumeMounts:
        - name: config-truststore
          mountPath: /opt/app/datafile/config/truststore.jks
          subPath: truststore.jks
        - name: config-cm
          mountPath: /opt/app/datafile/config/application.yaml
          subPath: application.yaml
        env:
        - name: APPID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: APPNS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_KAFKA_CLIENT-ID
          value: "datafile-collector.$(APPNS).$(APPID)"


